apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: deployment-name
spec:
  slotsPerWorker: 7 # node size in terms of CPUs - 1
  runPolicy:
    cleanPodPolicy: None # Running or All
  sshAuthMountPath: /home/mpiuser/.ssh
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
          - image: test
            name: hydraa-launcher
            securityContext:
              runAsUser: 1000
            command: ["mpirun"]
            args: []
            resources:
              limits:
                cpu: 1
                memory: 1Gi
    Worker:
      replicas: 2 # number of nodes per cluster (if you want to make all the cluster as MPI)
      template:
        spec:
          containers:
          - image: test
            name: hydraa-worker
            securityContext:
              runAsUser: 1000
            command:
            - /usr/sbin/sshd
            args:
            - -De
            - -f
            - /home/mpiuser/.sshd_config
            resources:
              requests:
                cpu: 7
                memory: 2Gi
              limits:
                cpu: 7
                memory: 3Gi