# This example demonstrates the ability to pass artifacts
# from one step to the next.
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: workflow-name
spec:
  entrypoint: entrypoint-name
  volumes:
  - name: workdir
    persistentVolumeClaim:
      claimName: hydraa-persistentvolumeclaim