name: CI

on:
  push:          
  pull_request:  

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.11'] # ['3.8', '3.9', '3.10', '3.11', '3.12']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m venv testenv
          . testenv/bin/activate
          python -m pip install --upgrade pip
          python -m pip install "setuptools==57.5.0" "packaging==21.3" wheel --force-reinstall
          python -m pip install -r requirements-ci.txt
          python -m pip install .

      - name: Run Unit tests
        run: |
          . testenv/bin/activate
          pytest -v tests 




